/**
 * Comprehensive research-backed quiz questions for all 6 categories.
 *
 * Research sources:
 * - Metacognitive Awareness Inventory (MAI) - Schraw & Dennison, 1994
 * - MSLQ - Motivated Strategies for Learning Questionnaire
 * - Test Anxiety Inventory (TAI) - Spielberger, 1980
 * - Grit Scale - Duckworth et al., 2007
 * - Goal Setting Theory - Locke & Latham
 * - VARK Learning Styles - Fleming
 */

// Standard Likert-5 options
const LIKERT_5 = [
  { value: 0, label: "Strongly Disagree" },
  { value: 1, label: "Disagree" },
  { value: 2, label: "Neutral" },
  { value: 3, label: "Agree" },
  { value: 4, label: "Strongly Agree" },
];

// Frequency options
const FREQUENCY = [
  { value: 0, label: "Never" },
  { value: 1, label: "Rarely" },
  { value: 2, label: "Sometimes" },
  { value: 3, label: "Often" },
  { value: 4, label: "Always" },
];

// ============================================================
// STUDY HABITS QUESTIONS (100+ questions)
// ============================================================

export const STUDY_HABITS_QUESTIONS = {
  environment: [
    { text: "I have a dedicated space specifically for studying.", format: "likert_5", weight: 3 },
    { text: "My study area is free from distractions like TV and excessive noise.", format: "likert_5", weight: 4 },
    { text: "I keep my study materials organized and easily accessible.", format: "likert_5", weight: 3 },
    { text: "I adjust lighting and temperature to optimize my focus.", format: "likert_5", weight: 2 },
    { text: "I remove my phone from my study space when working.", format: "likert_5", weight: 4 },
    { text: "My study environment is clean and clutter-free.", format: "likert_5", weight: 2 },
    { text: "I have all necessary supplies within reach when studying.", format: "likert_5", weight: 2 },
    { text: "I use noise-cancelling headphones or white noise to focus.", format: "likert_5", weight: 2 },
    { text: "I find studying in different locations beneficial for me.", format: "likert_5", weight: 2 },
    { text: "I ensure my chair and desk are ergonomically set up.", format: "likert_5", weight: 2 },
    { text: "I let others know not to disturb me during study time.", format: "likert_5", weight: 3 },
    { text: "I use apps or tools to block distracting websites.", format: "likert_5", weight: 3 },
    { text: "How often do you study in the same location?", format: "frequency", weight: 2 },
    { text: "How often do you clean your study area before starting?", format: "frequency", weight: 2 },
    { text: "How often do distractions interrupt your study sessions?", format: "frequency", weight: 4, isReversed: true },
  ],
  information_processing: [
    { text: "I actively summarize information in my own words while studying.", format: "likert_5", weight: 4 },
    { text: "I create connections between new material and what I already know.", format: "likert_5", weight: 4 },
    { text: "I break down complex topics into smaller, manageable parts.", format: "likert_5", weight: 3 },
    { text: "I ask myself questions about the material to test my understanding.", format: "likert_5", weight: 4 },
    { text: "I visualize concepts using diagrams or mental images.", format: "likert_5", weight: 3 },
    { text: "I relate new concepts to real-world examples.", format: "likert_5", weight: 3 },
    { text: "I identify the main ideas before diving into details.", format: "likert_5", weight: 3 },
    { text: "I pause periodically to reflect on what I've learned.", format: "likert_5", weight: 3 },
    { text: "I look for patterns and themes across different topics.", format: "likert_5", weight: 3 },
    { text: "I restate difficult concepts until I truly understand them.", format: "likert_5", weight: 4 },
    { text: "How often do you review material within 24 hours of learning it?", format: "frequency", weight: 4 },
    { text: "How often do you create your own examples for concepts?", format: "frequency", weight: 3 },
    { text: "How often do you explain concepts to others?", format: "frequency", weight: 4 },
    { text: "How often do you use analogies to understand new material?", format: "frequency", weight: 3 },
    { text: "How often do you highlight or underline key points?", format: "frequency", weight: 2 },
  ],
  technology_use: [
    { text: "I effectively use digital tools to organize my studies.", format: "likert_5", weight: 3 },
    { text: "I use apps to track my study time and productivity.", format: "likert_5", weight: 2 },
    { text: "I leverage online resources to supplement my learning.", format: "likert_5", weight: 3 },
    { text: "I back up my digital notes and materials regularly.", format: "likert_5", weight: 2 },
    { text: "I use spaced repetition apps for memorization.", format: "likert_5", weight: 4 },
    { text: "I am distracted by social media while studying.", format: "likert_5", weight: 4, isReversed: true },
    { text: "I use digital calendars to plan my study schedule.", format: "likert_5", weight: 3 },
    { text: "I watch educational videos to understand difficult concepts.", format: "likert_5", weight: 3 },
    { text: "I collaborate with classmates using online tools.", format: "likert_5", weight: 2 },
    { text: "I use AI tools appropriately to enhance my learning.", format: "likert_5", weight: 2 },
    { text: "How often do you check your phone while studying?", format: "frequency", weight: 4, isReversed: true },
    { text: "How often do you use flashcard apps?", format: "frequency", weight: 3 },
    { text: "How often do you record lectures for later review?", format: "frequency", weight: 2 },
    { text: "How often do you use focus timer apps (Pomodoro, etc.)?", format: "frequency", weight: 3 },
  ],
  learning_strategies: [
    { text: "I use spaced repetition to improve long-term retention.", format: "likert_5", weight: 5 },
    { text: "I practice active recall by testing myself frequently.", format: "likert_5", weight: 5 },
    { text: "I vary my study techniques based on the material type.", format: "likert_5", weight: 4 },
    { text: "I teach or explain concepts to others as a study method.", format: "likert_5", weight: 5 },
    { text: "I use practice problems to solidify my understanding.", format: "likert_5", weight: 4 },
    { text: "I create mind maps to visualize relationships between ideas.", format: "likert_5", weight: 3 },
    { text: "I interleave different subjects during study sessions.", format: "likert_5", weight: 3 },
    { text: "I use mnemonic devices for memorization.", format: "likert_5", weight: 3 },
    { text: "I review and correct my mistakes systematically.", format: "likert_5", weight: 4 },
    { text: "I connect new learning to prior knowledge.", format: "likert_5", weight: 4 },
    { text: "I study similar topics together for better understanding.", format: "likert_5", weight: 3 },
    { text: "I ask myself 'why' and 'how' questions to deepen understanding.", format: "likert_5", weight: 4 },
    { text: "How often do you review notes before class?", format: "frequency", weight: 3 },
    { text: "How often do you create practice tests for yourself?", format: "frequency", weight: 4 },
    { text: "How often do you study with past exams or quizzes?", format: "frequency", weight: 4 },
  ],
  self_assessment: [
    { text: "I can accurately predict my exam performance.", format: "likert_5", weight: 4 },
    { text: "I regularly evaluate whether my study methods are working.", format: "likert_5", weight: 4 },
    { text: "I adjust my study strategies based on performance feedback.", format: "likert_5", weight: 4 },
    { text: "I know which subjects require more of my study time.", format: "likert_5", weight: 3 },
    { text: "I seek feedback from instructors on my progress.", format: "likert_5", weight: 3 },
    { text: "I identify gaps in my understanding before exams.", format: "likert_5", weight: 4 },
    { text: "I reflect on my learning after completing each topic.", format: "likert_5", weight: 3 },
    { text: "I am aware of my strengths and weaknesses as a learner.", format: "likert_5", weight: 4 },
    { text: "I use rubrics to self-assess my work quality.", format: "likert_5", weight: 2 },
    { text: "I compare my actual study time to planned time.", format: "likert_5", weight: 3 },
    { text: "How often do you review your past performance?", format: "frequency", weight: 3 },
    { text: "How often do you adjust your study plan based on results?", format: "frequency", weight: 4 },
    { text: "How often do you ask for feedback on your work?", format: "frequency", weight: 3 },
  ],
  note_taking: [
    { text: "I take organized notes during lectures and readings.", format: "likert_5", weight: 3 },
    { text: "I use a consistent note-taking system (Cornell, outlining, etc.).", format: "likert_5", weight: 3 },
    { text: "I review and revise my notes within 24 hours.", format: "likert_5", weight: 4 },
    { text: "I highlight key concepts and main ideas in my notes.", format: "likert_5", weight: 2 },
    { text: "I add my own insights and questions to my notes.", format: "likert_5", weight: 3 },
    { text: "I create summaries of my notes for quick review.", format: "likert_5", weight: 3 },
    { text: "I use abbreviations and symbols to note-take efficiently.", format: "likert_5", weight: 2 },
    { text: "I reorganize my notes to improve clarity.", format: "likert_5", weight: 3 },
    { text: "I link notes from different classes when topics overlap.", format: "likert_5", weight: 3 },
    { text: "How often do you rewrite or type up handwritten notes?", format: "frequency", weight: 2 },
    { text: "How often do you review your notes before the next class?", format: "frequency", weight: 3 },
    { text: "How often do you use your notes to create study guides?", format: "frequency", weight: 3 },
  ],
};

// ============================================================
// LEARNING STYLE QUESTIONS (75+ questions)
// ============================================================

export const LEARNING_STYLE_QUESTIONS = {
  visual: [
    { text: "I learn best when information is presented with diagrams and charts.", format: "likert_5", weight: 4 },
    { text: "I prefer watching demonstrations rather than reading instructions.", format: "likert_5", weight: 3 },
    { text: "I use color-coding to organize my notes and materials.", format: "likert_5", weight: 3 },
    { text: "I create mental pictures to remember information.", format: "likert_5", weight: 4 },
    { text: "I understand concepts better through graphs and infographics.", format: "likert_5", weight: 4 },
    { text: "I remember faces better than names.", format: "likert_5", weight: 2 },
    { text: "I take detailed notes with drawings and symbols.", format: "likert_5", weight: 3 },
    { text: "I prefer textbooks with many illustrations.", format: "likert_5", weight: 3 },
    { text: "I visualize information when trying to remember it.", format: "likert_5", weight: 4 },
    { text: "I benefit from watching educational videos.", format: "likert_5", weight: 3 },
    { text: "I use mind maps to organize my thoughts.", format: "likert_5", weight: 3 },
    { text: "I prefer instructors who use visual aids.", format: "likert_5", weight: 3 },
    { text: "How often do you draw diagrams to understand concepts?", format: "frequency", weight: 4 },
    { text: "How often do you use highlighters when studying?", format: "frequency", weight: 2 },
    { text: "How often do you look for visual explanations online?", format: "frequency", weight: 3 },
  ],
  auditory: [
    { text: "I learn best by listening to lectures and discussions.", format: "likert_5", weight: 4 },
    { text: "I prefer verbal explanations over written instructions.", format: "likert_5", weight: 3 },
    { text: "I remember things better when I say them aloud.", format: "likert_5", weight: 4 },
    { text: "I benefit from participating in class discussions.", format: "likert_5", weight: 3 },
    { text: "I listen to educational podcasts to learn new topics.", format: "likert_5", weight: 3 },
    { text: "I read aloud when trying to memorize information.", format: "likert_5", weight: 3 },
    { text: "I prefer to explain ideas verbally rather than in writing.", format: "likert_5", weight: 3 },
    { text: "I remember names better than faces.", format: "likert_5", weight: 2 },
    { text: "I find it helpful to record and replay lectures.", format: "likert_5", weight: 3 },
    { text: "I think through problems by talking them out.", format: "likert_5", weight: 4 },
    { text: "I learn better when I can discuss topics verbally with others.", format: "likert_5", weight: 3 },
    { text: "I hum or talk to myself while studying.", format: "likert_5", weight: 2 },
    { text: "How often do you listen to recordings of lectures?", format: "frequency", weight: 3 },
    { text: "How often do you study by reciting information?", format: "frequency", weight: 3 },
    { text: "How often do you discuss concepts with classmates?", format: "frequency", weight: 3 },
  ],
  kinesthetic: [
    { text: "I learn best through hands-on activities and practice.", format: "likert_5", weight: 4 },
    { text: "I need to physically engage with material to understand it.", format: "likert_5", weight: 4 },
    { text: "I prefer labs and practical work over lectures.", format: "likert_5", weight: 3 },
    { text: "I find it hard to sit still for long periods while studying.", format: "likert_5", weight: 3 },
    { text: "I use physical objects or models to understand concepts.", format: "likert_5", weight: 3 },
    { text: "I take frequent breaks to move around during study.", format: "likert_5", weight: 3 },
    { text: "I remember things better when I've done them myself.", format: "likert_5", weight: 4 },
    { text: "I prefer to learn by doing rather than watching.", format: "likert_5", weight: 4 },
    { text: "I use gestures when explaining things to others.", format: "likert_5", weight: 2 },
    { text: "I write notes by hand rather than typing them.", format: "likert_5", weight: 2 },
    { text: "I benefit from study techniques that involve movement.", format: "likert_5", weight: 3 },
    { text: "I fidget or doodle while listening to lectures.", format: "likert_5", weight: 2 },
    { text: "How often do you use physical models for learning?", format: "frequency", weight: 3 },
    { text: "How often do you pace while studying?", format: "frequency", weight: 2 },
    { text: "How often do you learn through trial and error?", format: "frequency", weight: 3 },
  ],
  reading_writing: [
    { text: "I prefer learning through reading textbooks and articles.", format: "likert_5", weight: 4 },
    { text: "I take extensive notes and review them regularly.", format: "likert_5", weight: 4 },
    { text: "I learn best by writing summaries of what I've read.", format: "likert_5", weight: 4 },
    { text: "I prefer written instructions over verbal ones.", format: "likert_5", weight: 3 },
    { text: "I enjoy reading for pleasure and learning.", format: "likert_5", weight: 2 },
    { text: "I use lists to organize my thoughts and tasks.", format: "likert_5", weight: 3 },
    { text: "I understand concepts better when I write about them.", format: "likert_5", weight: 4 },
    { text: "I prefer essay exams over multiple choice.", format: "likert_5", weight: 2 },
    { text: "I rewrite my notes to help with memorization.", format: "likert_5", weight: 3 },
    { text: "I learn vocabulary by reading definitions.", format: "likert_5", weight: 3 },
    { text: "I prefer to communicate through email or text.", format: "likert_5", weight: 2 },
    { text: "How often do you read ahead in your textbooks?", format: "frequency", weight: 3 },
    { text: "How often do you write essays or reflections to learn?", format: "frequency", weight: 3 },
    { text: "How often do you make written study guides?", format: "frequency", weight: 4 },
  ],
  social: [
    { text: "I learn best when studying with others.", format: "likert_5", weight: 4 },
    { text: "I prefer group projects over individual work.", format: "likert_5", weight: 3 },
    { text: "I enjoy teaching concepts to classmates.", format: "likert_5", weight: 4 },
    { text: "I benefit from peer review and feedback.", format: "likert_5", weight: 3 },
    { text: "I am motivated by studying with friends.", format: "likert_5", weight: 3 },
    { text: "I prefer collaborative learning environments.", format: "likert_5", weight: 3 },
    { text: "I seek out study groups for difficult subjects.", format: "likert_5", weight: 3 },
    { text: "I understand material better after discussing it.", format: "likert_5", weight: 4 },
    { text: "I enjoy brainstorming with others.", format: "likert_5", weight: 3 },
    { text: "I ask others for help when I'm stuck.", format: "likert_5", weight: 3 },
    { text: "I am energized by working with classmates.", format: "likert_5", weight: 2 },
    { text: "How often do you study with a partner or group?", format: "frequency", weight: 4 },
    { text: "How often do you tutor or help classmates?", format: "frequency", weight: 3 },
    { text: "How often do you join online study communities?", format: "frequency", weight: 2 },
  ],
};

// ============================================================
// MOTIVATION QUESTIONS (80+ questions)
// ============================================================

export const MOTIVATION_QUESTIONS = {
  intrinsic: [
    { text: "I study subjects because I find them genuinely interesting.", format: "likert_5", weight: 4 },
    { text: "Learning new things gives me personal satisfaction.", format: "likert_5", weight: 4 },
    { text: "I pursue topics beyond what's required out of curiosity.", format: "likert_5", weight: 4 },
    { text: "I would study this subject even if it wasn't required.", format: "likert_5", weight: 3 },
    { text: "The joy of learning motivates me more than grades.", format: "likert_5", weight: 4 },
    { text: "I feel excited when learning something challenging.", format: "likert_5", weight: 4 },
    { text: "I study to understand, not just to pass exams.", format: "likert_5", weight: 4 },
    { text: "I enjoy intellectual challenges.", format: "likert_5", weight: 3 },
    { text: "I lose track of time when engaged in learning.", format: "likert_5", weight: 3 },
    { text: "I read books and articles outside of coursework.", format: "likert_5", weight: 3 },
    { text: "Learning itself is rewarding to me.", format: "likert_5", weight: 4 },
    { text: "How often do you explore topics beyond the syllabus?", format: "frequency", weight: 3 },
    { text: "How often do you feel excited about a new topic?", format: "frequency", weight: 3 },
  ],
  achievement: [
    { text: "I am motivated by getting high grades.", format: "likert_5", weight: 3 },
    { text: "Recognition for my academic work motivates me.", format: "likert_5", weight: 3 },
    { text: "I compare my performance to my classmates.", format: "likert_5", weight: 2 },
    { text: "I set achievement goals for each semester.", format: "likert_5", weight: 3 },
    { text: "Being at the top of my class is important to me.", format: "likert_5", weight: 2 },
    { text: "I am driven by the desire to outperform others.", format: "likert_5", weight: 2 },
    { text: "Earning academic honors motivates my studying.", format: "likert_5", weight: 3 },
    { text: "I track my GPA regularly.", format: "likert_5", weight: 2 },
    { text: "I feel proud when I excel in my studies.", format: "likert_5", weight: 3 },
    { text: "I am motivated by academic scholarships.", format: "likert_5", weight: 3 },
    { text: "Feedback on my performance affects my motivation.", format: "likert_5", weight: 3 },
    { text: "How often do you celebrate academic achievements?", format: "frequency", weight: 2 },
    { text: "How often do you check your grades?", format: "frequency", weight: 2 },
  ],
  social_motivation: [
    { text: "I am motivated by making my family proud.", format: "likert_5", weight: 3 },
    { text: "My friends' academic success motivates me.", format: "likert_5", weight: 3 },
    { text: "I feel accountable to mentors and teachers.", format: "likert_5", weight: 3 },
    { text: "Family expectations influence my study habits.", format: "likert_5", weight: 3 },
    { text: "I don't want to disappoint people who believe in me.", format: "likert_5", weight: 3 },
    { text: "Studying with motivated friends helps me stay on track.", format: "likert_5", weight: 3 },
    { text: "I feel pressure from my social circle to succeed.", format: "likert_5", weight: 2 },
    { text: "I share my academic goals with others for accountability.", format: "likert_5", weight: 3 },
    { text: "Community expectations influence my academic choices.", format: "likert_5", weight: 2 },
    { text: "How often do you discuss your goals with family?", format: "frequency", weight: 2 },
    { text: "How often do you study to meet others' expectations?", format: "frequency", weight: 2 },
  ],
  future_goals: [
    { text: "My career aspirations drive my academic effort.", format: "likert_5", weight: 4 },
    { text: "I connect my current studies to my future goals.", format: "likert_5", weight: 4 },
    { text: "I am motivated by the job opportunities my degree will provide.", format: "likert_5", weight: 3 },
    { text: "I visualize my future success to stay motivated.", format: "likert_5", weight: 3 },
    { text: "Long-term goals help me persist through challenges.", format: "likert_5", weight: 4 },
    { text: "I see education as an investment in my future.", format: "likert_5", weight: 4 },
    { text: "Financial stability motivates my academic work.", format: "likert_5", weight: 3 },
    { text: "I have a clear vision of where I want to be in 5 years.", format: "likert_5", weight: 4 },
    { text: "My current studies directly support my career path.", format: "likert_5", weight: 3 },
    { text: "I am motivated by potential graduate school opportunities.", format: "likert_5", weight: 2 },
    { text: "How often do you think about your future when studying?", format: "frequency", weight: 3 },
    { text: "How often do you research careers in your field?", format: "frequency", weight: 2 },
  ],
  autonomy: [
    { text: "I prefer to have control over how I study.", format: "likert_5", weight: 4 },
    { text: "I am motivated when I can choose my own projects.", format: "likert_5", weight: 3 },
    { text: "I set my own academic goals rather than following others.", format: "likert_5", weight: 4 },
    { text: "I prefer flexible deadlines over rigid schedules.", format: "likert_5", weight: 2 },
    { text: "I take ownership of my learning process.", format: "likert_5", weight: 4 },
    { text: "I am motivated by independence in my studies.", format: "likert_5", weight: 3 },
    { text: "I prefer self-directed learning over structured courses.", format: "likert_5", weight: 3 },
    { text: "I make my own decisions about what to study.", format: "likert_5", weight: 3 },
    { text: "Feeling in control increases my motivation.", format: "likert_5", weight: 4 },
    { text: "How often do you create your own study schedule?", format: "frequency", weight: 3 },
    { text: "How often do you pursue independent learning projects?", format: "frequency", weight: 3 },
  ],
  competence: [
    { text: "I am driven to master skills in my field.", format: "likert_5", weight: 4 },
    { text: "I persist until I fully understand difficult concepts.", format: "likert_5", weight: 4 },
    { text: "I aim to become an expert in my area of study.", format: "likert_5", weight: 4 },
    { text: "I take on challenging tasks to develop my abilities.", format: "likert_5", weight: 4 },
    { text: "Feeling competent in a subject motivates me.", format: "likert_5", weight: 4 },
    { text: "I continuously seek to improve my skills.", format: "likert_5", weight: 4 },
    { text: "I measure progress by how much I've learned, not grades.", format: "likert_5", weight: 3 },
    { text: "I enjoy becoming more skilled over time.", format: "likert_5", weight: 3 },
    { text: "I feel motivated when I notice improvement.", format: "likert_5", weight: 4 },
    { text: "How often do you practice skills to mastery?", format: "frequency", weight: 4 },
    { text: "How often do you seek challenging problems?", format: "frequency", weight: 3 },
  ],
};

// ============================================================
// FOCUS & ATTENTION QUESTIONS (70+ questions)
// ============================================================

export const FOCUS_ATTENTION_QUESTIONS = {
  sustained: [
    { text: "I can study for long periods without feeling mentally exhausted.", format: "likert_5", weight: 4 },
    { text: "I maintain focus throughout an entire lecture or study session.", format: "likert_5", weight: 4 },
    { text: "I can concentrate for hours when engaged in a task.", format: "likert_5", weight: 4 },
    { text: "My attention rarely wanders during important tasks.", format: "likert_5", weight: 4 },
    { text: "I can sustain effort on monotonous tasks.", format: "likert_5", weight: 3 },
    { text: "I finish what I start without losing focus.", format: "likert_5", weight: 4 },
    { text: "I can read for extended periods without my mind drifting.", format: "likert_5", weight: 3 },
    { text: "I feel mentally sharp throughout long study sessions.", format: "likert_5", weight: 3 },
    { text: "I can maintain concentration even when tired.", format: "likert_5", weight: 3 },
    { text: "My mind wanders frequently during study sessions.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you complete study sessions without breaks?", format: "frequency", weight: 3 },
    { text: "How often do you lose focus mid-task?", format: "frequency", weight: 4, isReversed: true },
  ],
  selective: [
    { text: "I can filter out distractions when studying.", format: "likert_5", weight: 4 },
    { text: "I focus on what's important and ignore the irrelevant.", format: "likert_5", weight: 4 },
    { text: "Background noise doesn't disrupt my concentration.", format: "likert_5", weight: 3 },
    { text: "I can study effectively in noisy environments.", format: "likert_5", weight: 3 },
    { text: "I prioritize high-value tasks over distractions.", format: "likert_5", weight: 4 },
    { text: "I resist the urge to check my phone while studying.", format: "likert_5", weight: 4 },
    { text: "I stay focused despite interruptions.", format: "likert_5", weight: 4 },
    { text: "I can concentrate when others are talking nearby.", format: "likert_5", weight: 3 },
    { text: "I quickly refocus after minor distractions.", format: "likert_5", weight: 4 },
    { text: "I get easily distracted by notifications.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do distractions interrupt your focus?", format: "frequency", weight: 4, isReversed: true },
    { text: "How often do you use distraction-blocking methods?", format: "frequency", weight: 3 },
  ],
  divided: [
    { text: "I can effectively multitask when needed.", format: "likert_5", weight: 3 },
    { text: "I can listen to a lecture while taking notes effectively.", format: "likert_5", weight: 4 },
    { text: "I handle multiple tasks simultaneously without losing quality.", format: "likert_5", weight: 3 },
    { text: "I can monitor multiple information sources at once.", format: "likert_5", weight: 2 },
    { text: "I balance different tasks without becoming overwhelmed.", format: "likert_5", weight: 3 },
    { text: "I can hold conversations while doing simple tasks.", format: "likert_5", weight: 2 },
    { text: "I manage competing demands on my attention well.", format: "likert_5", weight: 3 },
    { text: "I struggle when asked to do multiple things at once.", format: "likert_5", weight: 3, isReversed: true },
    { text: "How often do you successfully multitask?", format: "frequency", weight: 2 },
    { text: "How often do you lose track of tasks when multitasking?", format: "frequency", weight: 3, isReversed: true },
  ],
  alternating: [
    { text: "I can switch between different subjects quickly.", format: "likert_5", weight: 3 },
    { text: "I recover focus quickly after interruptions.", format: "likert_5", weight: 4 },
    { text: "I can rapidly shift attention between topics.", format: "likert_5", weight: 3 },
    { text: "Transitioning between tasks is easy for me.", format: "likert_5", weight: 3 },
    { text: "I adapt quickly to unexpected changes in my schedule.", format: "likert_5", weight: 3 },
    { text: "I can pause a task and resume it without difficulty.", format: "likert_5", weight: 3 },
    { text: "Context switching doesn't significantly impact my productivity.", format: "likert_5", weight: 3 },
    { text: "I lose my train of thought when switching tasks.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you switch between subjects in a session?", format: "frequency", weight: 2 },
    { text: "How often does switching tasks disrupt your focus?", format: "frequency", weight: 3, isReversed: true },
  ],
  deep_focus: [
    { text: "I can enter a state of deep focus on complex tasks.", format: "likert_5", weight: 4 },
    { text: "I lose track of time when deeply engaged in work.", format: "likert_5", weight: 4 },
    { text: "I feel completely absorbed in challenging tasks.", format: "likert_5", weight: 4 },
    { text: "I achieve 'flow state' during studying.", format: "likert_5", weight: 4 },
    { text: "Deep work sessions are my most productive time.", format: "likert_5", weight: 4 },
    { text: "I can focus intensely for extended periods.", format: "likert_5", weight: 4 },
    { text: "Complex problems energize rather than drain me.", format: "likert_5", weight: 3 },
    { text: "I deliberately create conditions for deep work.", format: "likert_5", weight: 4 },
    { text: "I struggle to get into a focused state.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you experience flow state?", format: "frequency", weight: 4 },
    { text: "How often do you block time for deep work?", format: "frequency", weight: 3 },
  ],
  environmental_sensitivity: [
    { text: "My focus is affected by the noise level around me.", format: "likert_5", weight: 3 },
    { text: "Lighting conditions impact my ability to concentrate.", format: "likert_5", weight: 2 },
    { text: "Temperature affects my productivity.", format: "likert_5", weight: 2 },
    { text: "I need a specific environment to focus well.", format: "likert_5", weight: 3 },
    { text: "Visual clutter distracts me from studying.", format: "likert_5", weight: 3 },
    { text: "I am sensitive to background conversations.", format: "likert_5", weight: 3 },
    { text: "Comfortable seating is important for my focus.", format: "likert_5", weight: 2 },
    { text: "I can concentrate in almost any environment.", format: "likert_5", weight: 3, isReversed: true },
    { text: "How often does your environment affect your focus?", format: "frequency", weight: 3 },
    { text: "How often do you adjust your environment before studying?", format: "frequency", weight: 2 },
  ],
};

// ============================================================
// GOAL SETTING QUESTIONS (60+ questions)
// ============================================================

export const GOAL_SETTING_QUESTIONS = {
  specificity: [
    { text: "I set specific, measurable academic goals.", format: "likert_5", weight: 4 },
    { text: "My goals have clear deadlines and milestones.", format: "likert_5", weight: 4 },
    { text: "I know exactly what I need to accomplish each week.", format: "likert_5", weight: 4 },
    { text: "I write down my goals rather than keeping them in my head.", format: "likert_5", weight: 3 },
    { text: "My goals are concrete enough to measure progress.", format: "likert_5", weight: 4 },
    { text: "I define success criteria for my academic goals.", format: "likert_5", weight: 4 },
    { text: "I break large goals into specific action items.", format: "likert_5", weight: 4 },
    { text: "I use numbers and dates in my goal statements.", format: "likert_5", weight: 3 },
    { text: "I clearly articulate what achieving my goal looks like.", format: "likert_5", weight: 3 },
    { text: "My goals are vague and general.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you set SMART goals?", format: "frequency", weight: 4 },
    { text: "How often do you review and refine your goals?", format: "frequency", weight: 3 },
  ],
  challenge_level: [
    { text: "I set goals that push me beyond my comfort zone.", format: "likert_5", weight: 4 },
    { text: "My goals are challenging but achievable.", format: "likert_5", weight: 4 },
    { text: "I avoid setting goals that are too easy.", format: "likert_5", weight: 3 },
    { text: "I am motivated by ambitious targets.", format: "likert_5", weight: 4 },
    { text: "I stretch my abilities with difficult goals.", format: "likert_5", weight: 4 },
    { text: "I set goals that require growth and learning.", format: "likert_5", weight: 4 },
    { text: "I balance ambition with realism in goal-setting.", format: "likert_5", weight: 4 },
    { text: "I feel energized by challenging goals.", format: "likert_5", weight: 3 },
    { text: "I set easy goals to guarantee success.", format: "likert_5", weight: 3, isReversed: true },
    { text: "How often do you set goals that challenge you?", format: "frequency", weight: 4 },
    { text: "How often do you achieve challenging goals?", format: "frequency", weight: 3 },
  ],
  progress_monitoring: [
    { text: "I regularly track progress toward my goals.", format: "likert_5", weight: 4 },
    { text: "I review my goals weekly or more often.", format: "likert_5", weight: 4 },
    { text: "I use tracking tools to monitor my progress.", format: "likert_5", weight: 3 },
    { text: "I celebrate milestones along the way to my goals.", format: "likert_5", weight: 3 },
    { text: "I know at any time how close I am to my goals.", format: "likert_5", weight: 4 },
    { text: "I set regular check-in points for goal review.", format: "likert_5", weight: 4 },
    { text: "I visualize my progress with charts or graphs.", format: "likert_5", weight: 2 },
    { text: "I rarely review my progress.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you check your goal progress?", format: "frequency", weight: 4 },
    { text: "How often do you update your goal tracking?", format: "frequency", weight: 3 },
  ],
  implementation_intentions: [
    { text: "I plan specific times for working toward my goals.", format: "likert_5", weight: 4 },
    { text: "I use 'if-then' planning for my goals.", format: "likert_5", weight: 4 },
    { text: "I know exactly when and where I'll work on my goals.", format: "likert_5", weight: 4 },
    { text: "I anticipate obstacles and plan how to overcome them.", format: "likert_5", weight: 4 },
    { text: "I link new habits to existing routines.", format: "likert_5", weight: 3 },
    { text: "I have contingency plans for my goals.", format: "likert_5", weight: 3 },
    { text: "I schedule specific times for studying in my calendar.", format: "likert_5", weight: 4 },
    { text: "I plan the first step I'll take toward each goal.", format: "likert_5", weight: 4 },
    { text: "How often do you create detailed action plans?", format: "frequency", weight: 4 },
    { text: "How often do you use scheduling to support goals?", format: "frequency", weight: 4 },
  ],
  adjustment: [
    { text: "I adjust my goals based on new information.", format: "likert_5", weight: 3 },
    { text: "I modify my approach when strategies aren't working.", format: "likert_5", weight: 4 },
    { text: "I am flexible in how I achieve my goals.", format: "likert_5", weight: 3 },
    { text: "I learn from setbacks and adjust my plans.", format: "likert_5", weight: 4 },
    { text: "I revise unrealistic goals to be more achievable.", format: "likert_5", weight: 3 },
    { text: "I adapt my goals when circumstances change.", format: "likert_5", weight: 3 },
    { text: "I seek feedback to improve my goal pursuit.", format: "likert_5", weight: 4 },
    { text: "I continue pursuing goals even when they're not working.", format: "likert_5", weight: 3, isReversed: true },
    { text: "How often do you revise your goals?", format: "frequency", weight: 3 },
    { text: "How often do you change strategies while pursuing a goal?", format: "frequency", weight: 3 },
  ],
};

// ============================================================
// STRESS & ANXIETY QUESTIONS (70+ questions)
// ============================================================

export const STRESS_ANXIETY_QUESTIONS = {
  test_worry: [
    { text: "I worry about failing exams even when I've prepared well.", format: "likert_5", weight: 4 },
    { text: "During tests, I think about the consequences of doing poorly.", format: "likert_5", weight: 4 },
    { text: "I compare my performance to others during exams.", format: "likert_5", weight: 3 },
    { text: "My mind goes blank during tests even when I know the material.", format: "likert_5", weight: 4 },
    { text: "I have intrusive thoughts about failure during exams.", format: "likert_5", weight: 4 },
    { text: "I worry about time running out during tests.", format: "likert_5", weight: 3 },
    { text: "I think about what others will think if I fail.", format: "likert_5", weight: 3 },
    { text: "Negative thoughts interfere with my concentration on tests.", format: "likert_5", weight: 4 },
    { text: "I imagine the worst possible outcomes for exams.", format: "likert_5", weight: 4 },
    { text: "I feel calm and focused during exams.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you have negative thoughts during tests?", format: "frequency", weight: 4 },
    { text: "How often does worry affect your exam performance?", format: "frequency", weight: 4 },
  ],
  emotionality: [
    { text: "I experience physical symptoms (racing heart, sweating) before exams.", format: "likert_5", weight: 4 },
    { text: "My hands shake during important tests.", format: "likert_5", weight: 3 },
    { text: "I feel nauseous before major exams.", format: "likert_5", weight: 3 },
    { text: "I have trouble sleeping before exams.", format: "likert_5", weight: 4 },
    { text: "My heart races when I sit down to take a test.", format: "likert_5", weight: 4 },
    { text: "I feel physically tense during exams.", format: "likert_5", weight: 4 },
    { text: "I experience headaches during stressful academic periods.", format: "likert_5", weight: 3 },
    { text: "My breathing becomes shallow during tests.", format: "likert_5", weight: 3 },
    { text: "I feel calm physically during exams.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you experience physical anxiety symptoms?", format: "frequency", weight: 4 },
    { text: "How often does stress affect your sleep?", format: "frequency", weight: 3 },
  ],
  coping_mechanisms: [
    { text: "I use relaxation techniques to manage stress.", format: "likert_5", weight: 4 },
    { text: "I have healthy outlets for academic stress.", format: "likert_5", weight: 4 },
    { text: "I practice deep breathing or meditation for stress relief.", format: "likert_5", weight: 4 },
    { text: "I exercise to reduce stress.", format: "likert_5", weight: 3 },
    { text: "I talk to friends or family about academic stress.", format: "likert_5", weight: 3 },
    { text: "I maintain a healthy sleep schedule despite stress.", format: "likert_5", weight: 4 },
    { text: "I take breaks to prevent burnout.", format: "likert_5", weight: 4 },
    { text: "I have strategies to calm myself before exams.", format: "likert_5", weight: 4 },
    { text: "I avoid unhealthy ways of coping with stress, such as excessive caffeine or skipping meals.", format: "likert_5", weight: 3 },
    { text: "How often do you use stress-reduction techniques?", format: "frequency", weight: 4 },
    { text: "How often do you take mental health breaks?", format: "frequency", weight: 3 },
  ],
  resilience: [
    { text: "I recover quickly from academic setbacks.", format: "likert_5", weight: 4 },
    { text: "I maintain perspective during stressful academic times.", format: "likert_5", weight: 4 },
    { text: "I view failures as learning opportunities.", format: "likert_5", weight: 4 },
    { text: "I bounce back from poor grades without losing motivation.", format: "likert_5", weight: 4 },
    { text: "I don't let one bad exam affect my overall confidence.", format: "likert_5", weight: 4 },
    { text: "I persist through academic challenges.", format: "likert_5", weight: 4 },
    { text: "I see difficult courses as opportunities for growth.", format: "likert_5", weight: 3 },
    { text: "I adapt to unexpected academic challenges.", format: "likert_5", weight: 4 },
    { text: "Bad grades significantly lower my motivation.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you recover quickly from setbacks?", format: "frequency", weight: 4 },
    { text: "How often do you view challenges positively?", format: "frequency", weight: 3 },
  ],
  academic_buoyancy: [
    { text: "I handle everyday academic pressures well.", format: "likert_5", weight: 4 },
    { text: "I manage multiple deadlines without excessive stress.", format: "likert_5", weight: 4 },
    { text: "I stay calm when facing academic challenges.", format: "likert_5", weight: 4 },
    { text: "I don't let small setbacks derail my progress.", format: "likert_5", weight: 4 },
    { text: "I maintain my routine during busy academic periods.", format: "likert_5", weight: 4 },
    { text: "I deal with critical feedback constructively.", format: "likert_5", weight: 4 },
    { text: "I stay organized even when things are hectic.", format: "likert_5", weight: 3 },
    { text: "I keep my cool when grades are posted.", format: "likert_5", weight: 3 },
    { text: "I get overwhelmed by typical academic demands.", format: "likert_5", weight: 4, isReversed: true },
    { text: "How often do you handle academic pressure well?", format: "frequency", weight: 4 },
    { text: "How often do everyday challenges affect your mood?", format: "frequency", weight: 3, isReversed: true },
  ],
};

// Helper function to get options based on format
export function getOptionsForFormat(format: string) {
  return format === "frequency" ? FREQUENCY : LIKERT_5;
}

// Export all question sets
export const ALL_QUESTION_SETS = {
  study_habits: STUDY_HABITS_QUESTIONS,
  learning_style: LEARNING_STYLE_QUESTIONS,
  motivation: MOTIVATION_QUESTIONS,
  focus_attention: FOCUS_ATTENTION_QUESTIONS,
  goal_setting: GOAL_SETTING_QUESTIONS,
  stress_anxiety: STRESS_ANXIETY_QUESTIONS,
};
