/**
 * 9-Layer Parallax Asset Registry (AUTO-GENERATED by /tmp/gen-registry.mjs)
 *
 * React Native needs static require() literals. Each biome exposes its 9 layer
 * slots; clouds/trees/bushes/ground are variant arrays that the renderer cycles
 * through as the scene scrolls.
 */
import { ImageSourcePropType } from "react-native";

export type NineLayerBiome =
  | "desert"
  | "forest"
  | "beach"
  | "volcano"
  | "snow"
  | "canyon"
  | "northern"
  | "galaxy";

export interface NineLayerSet {
  sky: ImageSourcePropType;
  sun: ImageSourcePropType;
  clouds: ImageSourcePropType[];
  farMountains: ImageSourcePropType;
  midMountains: ImageSourcePropType;
  midground: ImageSourcePropType;
  trees: ImageSourcePropType[];
  bushes: ImageSourcePropType[];
  ground: ImageSourcePropType[];
}

export const NINE_LAYER_ASSETS: Record<NineLayerBiome, NineLayerSet> = {
  desert: {
    sky: require("../../assets/Background_animations/Desert/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Desert/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Desert/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Desert/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Desert/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Desert/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Desert/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Desert/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Desert/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Desert/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  forest: {
    sky: require("../../assets/Background_animations/Forest/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Forest/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Forest/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Forest/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Forest/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Forest/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Forest/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Forest/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Forest/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Forest/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  beach: {
    sky: require("../../assets/Background_animations/Beach/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Beach/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Beach/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Beach/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Beach/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Beach/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Beach/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Beach/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Beach/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Beach/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  volcano: {
    sky: require("../../assets/Background_animations/Volcano/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Volcano/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Volcano/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Volcano/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Volcano/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Volcano/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Volcano/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Volcano/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Volcano/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  snow: {
    sky: require("../../assets/Background_animations/Snow/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Snow/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Snow/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Snow/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Snow/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Snow/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Snow/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Snow/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Snow/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Snow/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  canyon: {
    sky: require("../../assets/Background_animations/Canyon/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Canyon/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Canyon/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Canyon/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Canyon/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Canyon/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Canyon/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Canyon/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Canyon/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  northern: {
    sky: require("../../assets/Background_animations/Northern/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Northern/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Northern/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Northern/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Northern/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Northern/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Northern/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Northern/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Northern/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Northern/nine_layer/stones_pebbles_path.webp"),
    ],
  },
  galaxy: {
    sky: require("../../assets/Background_animations/Galaxy/nine_layer/sky_gradient.webp"),
    sun: require("../../assets/Background_animations/Galaxy/nine_layer/sun.webp"),
    clouds: [
      require("../../assets/Background_animations/Galaxy/nine_layer/fluffy_cloud.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/dense_layered_cloud.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/small_cloud.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/thin_wisp_cloud.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/wide_cloud.webp"),
    ],
    farMountains: require("../../assets/Background_animations/Galaxy/nine_layer/far_mountain_range.webp"),
    midMountains: require("../../assets/Background_animations/Galaxy/nine_layer/mid_mountain_range.webp"),
    midground: require("../../assets/Background_animations/Galaxy/nine_layer/mid_jungle_layer.webp"),
    trees: [
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_tree.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_tall_tree.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_left_lean_tree.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_right_lean_tree.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_right_trunk_bend_left.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_trunk_bend_right.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_trunk_s.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_long_vine_tree.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/foreground_vines_tree.webp"),
    ],
    bushes: [
      require("../../assets/Background_animations/Galaxy/nine_layer/jungle_bush.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/tall_bush.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/wide_low_bush.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/thick_moss_bush.webp"),
    ],
    ground: [
      require("../../assets/Background_animations/Galaxy/nine_layer/regular_path.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/mossy_jungl_path.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/grassy_path.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/damp_moss_path.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/flower_jungl_path.webp"),
      require("../../assets/Background_animations/Galaxy/nine_layer/stones_pebbles_path.webp"),
    ],
  },
};

export const NINE_LAYER_BIOMES: NineLayerBiome[] = [
  "forest",
  "beach",
  "desert",
  "volcano",
  "snow",
  "canyon",
  "northern",
  "galaxy",
];

export function hasNineLayerSet(
  biome: string | undefined,
): biome is NineLayerBiome {
  return !!biome && biome in NINE_LAYER_ASSETS;
}
