name: Build and Deploy iOS App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_ios:
    name: Build iOS app
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build iOS app
        run: eas build --platform ios --non-interactive --profile production
        id: build
        env:
          EAS_BUILD_AUTOCOMMIT: 1

      - name: Output build ID
        run: |
          echo "Build completed successfully"
          echo "build_id=${{ steps.build.outputs.build_id }}" >> $GITHUB_OUTPUT

    outputs:
      build_id: ${{ steps.build.outputs.build_id }}

  submit_ios:
    name: Submit to Apple App Store
    needs: [build_ios]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Submit to App Store
        run: eas submit --platform ios --non-interactive --id ${{ needs.build_ios.outputs.build_id }}
        env:
          EXPO_APPLE_ID: ${{ secrets.EXPO_APPLE_ID }}
          EXPO_ASC_KEY_ID: ${{ secrets.EXPO_ASC_KEY_ID }}
          EXPO_ASC_ISSUER_ID: ${{ secrets.EXPO_ASC_ISSUER_ID }}
          EXPO_ASC_KEY: ${{ secrets.EXPO_ASC_KEY }}
